[application]
name = "Nearby"
asset_dir = "assets"

[application.desktop]
default_platform = "auto"

[web.app]

# HTML title tag content
title = "Nearby"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
